[DBConfig]
DBDir = "sqlite"
Driver = "sqlite3"
DBFile = "sqlite\\base.db"

[ServerHost]
Port = ":8080"
Host = "https://short.com"
Redirect = "/redirect/"

[ApiSecure]
ApiKey = "777"
ApiHeader = "x-api-key"
