[DBConfig]
DBDir = "sqlite"
Driver = "sqlite3"
#win
DBFile = "sqlite\\base.db"
#linux
#DBFile = "./sqlite/base.db"

[ServerHost]
Port = ":8080"
Host = "https://short.com/"

[ApiSecure]
ApiKey = "777"
ApiHeader = "x-api-key"
